language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t hashiinngg/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true hashiinngg/docker-react npm run test -- --coverage

deploy:
  app: "docker-react"
  provider: elasticbeanstalk
  region: "us-east-1"
  name: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-106576526789"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"